[package]
name = "wfe-rustlang"
version = "1.9.1"
edition = "2024"
license = "MIT"
repository = "https://src.sunbeam.pt/studio/wfe"
homepage = "https://src.sunbeam.pt/studio/wfe"
description = "Rust toolchain step executors (cargo, rustup) for WFE"

[dependencies]
wfe-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
rustdoc-types = "0.38"

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["test-util", "process"] }
tempfile = { workspace = true }
