[workspace]
members = ["wfe-core", "wfe-sqlite", "wfe-postgres", "wfe-opensearch", "wfe-valkey", "wfe", "wfe-yaml", "wfe-buildkit", "wfe-containerd", "wfe-containerd-protos", "wfe-buildkit-protos", "wfe-rustlang", "wfe-server-protos", "wfe-server", "wfe-deno", "wfe-kubernetes"]
resolver = "2"

[workspace.package]
version = "1.7.0"
edition = "2024"
license = "MIT"
repository = "https://src.sunbeam.pt/studio/wfe"
homepage = "https://src.sunbeam.pt/studio/wfe"

[workspace.dependencies]
# Core
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.28"
opentelemetry = "0.27"
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.27", features = ["tonic"] }

# HTTP
reqwest = { version = "0.12", features = ["json"] }

# Persistence
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "sqlite", "postgres", "chrono", "uuid", "json"] }

# Redis/Valkey
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }

# Search
opensearch = "2"

# Internal crates
wfe-core = { version = "1.7.0", path = "wfe-core", registry = "sunbeam" }
wfe-sqlite = { version = "1.7.0", path = "wfe-sqlite", registry = "sunbeam" }
wfe-postgres = { version = "1.7.0", path = "wfe-postgres", registry = "sunbeam" }
wfe-opensearch = { version = "1.7.0", path = "wfe-opensearch", registry = "sunbeam" }
wfe-valkey = { version = "1.7.0", path = "wfe-valkey", registry = "sunbeam" }
wfe-yaml = { version = "1.7.0", path = "wfe-yaml", registry = "sunbeam" }
wfe-buildkit = { version = "1.7.0", path = "wfe-buildkit", registry = "sunbeam" }
wfe-containerd = { version = "1.7.0", path = "wfe-containerd", registry = "sunbeam" }
wfe-rustlang = { version = "1.7.0", path = "wfe-rustlang", registry = "sunbeam" }

# YAML
serde_yaml = "0.9"
yaml-merge-keys = { version = "0.8", features = ["serde_yaml"] }
regex = "1"

# Deno runtime
deno_core = "0.394"
deno_error = "0.7"
url = "2"

# Kubernetes
kube = { version = "3.1", features = ["runtime", "client", "ws"] }
k8s-openapi = { version = "0.27", features = ["latest"] }
futures = "0.3"

# Dev/Test
pretty_assertions = "1"
rstest = "0.23"
wiremock = "0.6"
tokio-stream = "0.1"
tempfile = "3"
