[package]
name = "wfe"
version = "1.9.1"
edition.workspace = true
license.workspace = true
repository = "https://github.com/sunbeamdotpt/sunbeam"
homepage = "https://github.com/sunbeamdotpt/sunbeam"
description = "WFE workflow engine - umbrella crate"

[features]
default = []
otel = [
    "wfe-core/otel",
    "opentelemetry",
    "opentelemetry_sdk",
    "opentelemetry-otlp",
    "tracing-opentelemetry",
    "tracing-subscriber/registry",
]

[dependencies]
wfe-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio-util = "0.7"

tracing-subscriber = { workspace = true }

# OTel (optional, behind "otel" feature)
tracing-opentelemetry = { workspace = true, optional = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true }

[dev-dependencies]
wfe-core = { workspace = true, features = ["test-support"] }
wfe-sqlite = { workspace = true }
wfe-yaml = { workspace = true, features = ["deno"] }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
wiremock = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
