[package]
name = "wfe-containerd"
version = "1.9.4"
edition.workspace = true
license.workspace = true
repository = "https://github.com/sunbeamdotpt/sunbeam"
homepage = "https://github.com/sunbeamdotpt/sunbeam"
description = "containerd container runner executor for WFE"

[dependencies]
wfe-core = { workspace = true }
wfe-containerd-protos = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tonic = "0.14"
tower = "0.5"
hyper-util = { version = "0.1", features = ["tokio"] }
prost-types = "0.14"
uuid = { version = "1", features = ["v4"] }
sha2 = "0.10"
tokio-stream = "0.1"

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
tempfile = { workspace = true }
tokio-util = "0.7"
