[package]
name = "wfe-core"
version = "1.10.0"
edition.workspace = true
license.workspace = true
repository = "https://github.com/sunbeamdotpt/wfe"
homepage = "https://github.com/sunbeamdotpt/wfe"
description = "Core traits, models, builder, and executor for the WFE workflow engine"

[features]
default = []
test-support = []
otel = ["tracing-opentelemetry", "opentelemetry"]

[dependencies]
tracing-opentelemetry = { workspace = true, optional = true }
opentelemetry = { workspace = true, optional = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio-util = "0.7"
bytes = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
