[package]
name = "wfe-buildkit-protos"
version = "1.9.4"
edition.workspace = true
license.workspace = true
repository = "https://github.com/sunbeamdotpt/sunbeam"
homepage = "https://github.com/sunbeamdotpt/sunbeam"
description = "Generated gRPC stubs for the full BuildKit API"

[dependencies]
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"

[build-dependencies]
tonic-build = "0.14"
tonic-prost-build = "0.14"
prost-build = "0.14"
